name: Deploy pebblingnewui to Railway

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Updated to a more current LTS version, adjust if needed

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # Or your project's pnpm version

      - name: Install dependencies
        run: pnpm install

      - name: Run linters
        run: pnpm lint # Adjust if your lint script has a different name

      # - name: Run tests
      #   run: pnpm test # Adjust if your test script has a different name

      - name: Build project
        run: pnpm build # Adjust if your build script has a different name

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # Login to Railway using the token
          railway login ${{ secrets.RAILWAY_TOKEN }}
          # Link the project using the service ID
          railway link ${{ secrets.RAILWAY_SERVICE_ID }}
          # Deploy the application
          railway up --detach
